### ISSUE TITLE
Cant flash

### ISSUE THREAD

**Issue by Zynth9999** [Xinyuan-LilyGO/T-HMI#29]
I keep getting this error in esptool:
`A fatal error occurred: Unable to verify flash chip connection (No serial data received.).`

**Comment by lewisxhe** [comment]
Try the following steps
![image](https://github.com/user-attachments/assets/297a099f-3ff2-4a2c-abf3-fdbd713010de)

**Comment by Zynth9999** [comment]
Will try and post an update

**Comment by Zynth9999** [comment]
```
"C:\Users\Janek\AppData\Local\Arduino15\packages\esp32\tools\esptool_py\4.6/esptool.exe" --chip esp32s3 --port "COM20" --baud 921600  --before default_reset --after hard_reset write_flash  -z --flash_mode keep --flash_freq keep --flash_size keep 0x0 "C:\Users\Janek\AppData\Local\Temp\arduino\sketches\D91E7C3EAC94FB9D10797C98D684CEFC/BareMinimum.ino.bootloader.bin" 0x8000 "C:\Users\Janek\AppData\Local\Temp\arduino\sketches\D91E7C3EAC94FB9D10797C98D684CEFC/BareMinimum.ino.partitions.bin" 0xe000 "C:\Users\Janek\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.4/tools/partitions/boot_app0.bin" 0x10000 "C:\Users\Janek\AppData\Local\Temp\arduino\sketches\D91E7C3EAC94FB9D10797C98D684CEFC/BareMinimum.ino.bin" 
esptool.py v4.6
Serial port COM20
Connecting...Traceback (most recent call last):
  File "esptool.py", line 37, in <module>
  File "esptool\__init__.py", line 1064, in _main
  File "esptool\__init__.py", line 859, in main
  File "esptool\cmds.py", line 466, in write_flash
  File "esptool\util.py", line 37, in flash_size_bytes
TypeError: argument of type 'NoneType' is not iterable

Chip is ESP32-S3 (revision v0.1)
Features: WiFi, BLE
Crystal is 40MHz
MAC: 34:85:18:a9:dd:d8
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 921600
Changed.
Configuring flash size...
[8284] Failed to execute script 'esptool' due to unhandled exception!
Failed uploading: uploading error: exit status 1
```
Looks like a problem with setting the flash size

**Comment by lewisxhe** [comment]
Try the espressif upload tool and upload the firmware we provide. Try it
https://github.com/Xinyuan-LilyGO/T-HMI/tree/master/firmware

**Comment by Zynth9999** [comment]
```
D:\flash_download_tool_3.9.5_0\flash_download_tool_3.9.5
D:\firmware.bin
1 kill
test offset :  0 0x0
case ok
test offset :  0 0x0
case ok

Uploading stub...
Running stub...
Stub running...
Changing baud rate to 115200
Changed.
NO XMC flash  detected!
SPI_BOOT_CRYPT_CNT 0
SECURE_BOOT_EN False
Compressed 1229040 bytes to 688625...
[2024-10-14 11:37:07,920][ESP8266Loader_spi[1]][espDownloader.py][line:774][ERROR]: ESP32S3 Chip flash download error esp_write_flash.

```
![image](https://github.com/user-attachments/assets/080c4dfe-a43e-48e1-93b0-d1ad943ad43d)

Still get errors

**Comment by lewisxhe** [comment]
Did you connect any sensors?

**Comment by Zynth9999** [comment]
Nope, just the barebones board

**Comment by lewisxhe** [comment]
If no sensor is connected, it may be damaged. Contact your dealer.

**Comment by Zynth9999** [comment]
Ok will do

**Comment by Zynth9999** [comment]
The seller i bough it from doesn't see my order, but i can send you a detailed picture of the board

**Comment by lewisxhe** [comment]
What pictures? I can't handle after-sales issues, I can only handle technical issues.

From the above conversation, it can be judged that there is a problem with the board, you need to contact the dealer for replacement

**Comment by Zynth9999** [comment]
No i mean is there something wrong with the chip? A missing resistor or something

**Comment by Zynth9999** [comment]
Ah ok well sorry for wasting your time with this
